#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

# #  use the fact that even terms follow the relation: E_k = 4*E_{k-1} + E_{k-2}

import time
time_start = time.time()

a , b = 2, 8
total_sum = 0

while a <= 4000000:
    total_sum += a
    a, b = b, 4 * b + a

print(f"Sum: {total_sum}")

end = time.time()
print(f"Finished in {end - time_start} seconds.")